# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: "TCP"
      port: 3001
      targetPort: 8080
---
# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2 # Adjust as needed
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your_backend_image:latest
          ports:
            - containerPort: 3001
          env:
            - name: PGUSER
              value: your_username
            - name: PGPASSWORD
              value: your_password
            # Add other environment variables for database connection
